import React from 'react';
import { getTranslation as t } from '../i18n';

export default function RiskReport({ duration, symptoms, lang, patientData, aiResult }) {
  const calculateRisk = () => {
    // If AI Result exists, prioritize it
    if (aiResult && aiResult.status) {
      if (aiResult.status === 'Tuberculosis') {
        return { level: 'HIGH', class: 'risk-very-high', note: aiResult.details };
      } else {
        return { level: 'LOW', class: 'risk-low', note: aiResult.details };
      }
    }

    const hasProlongedCough = symptoms.coughDuration > 14;
    const hasMediumCough = symptoms.coughDuration >= 7 && symptoms.coughDuration <= 14;
    const hasHemoptysis = symptoms.hemoptysis;
    const isMultipleVisits = duration > 2;
    const hasTbContact = symptoms.tbContact === 'Yes';
    
    let basicSymptomsCount = 0;
    if (symptoms.coughDuration > 0) basicSymptomsCount++;
    if (symptoms.fever) basicSymptomsCount++;
    if (symptoms.weightLoss) basicSymptomsCount++;
    if (symptoms.nightSweats) basicSymptomsCount++;
    
    if (hasProlongedCough || hasHemoptysis || isMultipleVisits || hasTbContact) {
      return { level: 'HIGH', class: 'risk-very-high' };
    }
    
    if ((basicSymptomsCount >= 2 && basicSymptomsCount <= 3) || hasMediumCough) {
      return { level: 'MODERATE', class: 'risk-high' };
    }
    
    return { level: 'LOW', class: 'risk-low' };
  };

  const risk = calculateRisk();

  const getAiActionableInsights = () => {
    switch (risk.level) {
      case 'HIGH': return t(lang, 'aiHighRisk');
      case 'MODERATE': return t(lang, 'aiModerateRisk');
      default: return t(lang, 'aiLowRisk');
    }
  };

  const getRecommendationsArray = () => {
    switch (risk.level) {
      case 'HIGH':
        return [t(lang, 'urgentRef'), t(lang, 'referCbnaat'), t(lang, 'mask')];
      case 'MODERATE':
        return [t(lang, 'monitor'), t(lang, 'antibiotics'), t(lang, 'reeval')];
      case 'LOW':
        return [t(lang, 'generalObs')];
      default: return [];
    }
  };

  const downloadReport = () => {
    const activeSymptomsList = Object.entries(symptoms)
      .filter(([k, v]) => v === true)
      .map(([k]) => t('en', k))
      .join(', ');

    const reportText = `
------------------------------------------------
TB CLINICAL RISK REPORT (AI ASSISTED)
------------------------------------------------
Patient Name: ${patientData.patientName}
Age: ${patientData.age}
Gender: ${patientData.gender}
Location: ${patientData.location || 'N/A'}
Phone: ${patientData.phone || 'N/A'}
Occupation: ${patientData.occupation || 'N/A'}
TB Contact History: ${patientData.tbContact}

Number of visits: ${duration}
Cough Duration: ${symptoms.coughDuration} days
Active Symptoms: ${activeSymptomsList || 'None'}

------------------------------------------------
RISK ASSESSMENT OUTCOME
------------------------------------------------
Risk Level: ${risk.level} RISK

AI Actionable Insight: 
${getAiActionableInsights()}

Recommendations:
${getRecommendationsArray().map(r => '- ' + r).join('\n')}

Disclaimer: This report was generated by an AI-assisted screening tool and is not a confirmed medical diagnosis.
------------------------------------------------
    `;
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${patientData.patientName.replace(/\s+/g, '_')}_TB_Report.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ padding: '2rem', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(15, 23, 42, 0.4)', position: 'relative', overflow: 'hidden' }}>
      <div style={{ position: 'absolute', top: 0, right: 0, padding: '1rem', fontSize: '0.8rem', opacity: 0.5 }}>AI RISK ENGINE v4.2</div>
      
      <h3 style={{ color: 'var(--primary-cyan)', marginBottom: '1rem', textTransform: 'uppercase', letterSpacing: '1px' }}>{t(lang, 'riskLevel')}</h3>
      <div style={{ fontSize: '3rem', fontWeight: '900', color: risk.level === 'HIGH' ? 'var(--neon-red)' : (risk.level === 'MODERATE' ? 'var(--neon-orange)' : 'var(--neon-green)'), textShadow: `0 0 20px ${risk.level === 'HIGH' ? 'rgba(239, 68, 68, 0.5)' : (risk.level === 'MODERATE' ? 'rgba(245, 158, 11, 0.5)' : 'rgba(16, 185, 129, 0.5)')}` }}>
        {risk.level} RISK
      </div>
      
      <div style={{ marginTop: '2rem', background: 'rgba(255, 255, 255, 0.03)', padding: '1.5rem', borderRadius: '12px', borderLeft: `4px solid ${risk.level === 'HIGH' ? 'var(--neon-red)' : (risk.level === 'MODERATE' ? 'var(--neon-orange)' : 'var(--neon-green)')}` }}>
        <p style={{ fontSize: '1rem', color: 'var(--text-main)', lineHeight: '1.5' }}>
          {risk.note ? <strong>{risk.note}. </strong> : ''}
          {getAiActionableInsights()}
        </p>
      </div>

      <div style={{ marginTop: '1.5rem', background: 'rgba(255, 255, 255, 0.02)', padding: '1.5rem', borderRadius: '12px' }}>
        <h4 style={{ marginBottom: '1rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '0.5rem', color: 'var(--text-muted)' }}>
          {t(lang, 'recommendations')}
        </h4>
        <ul style={{ paddingLeft: '20px', margin: 0, color: 'var(--text-main)', display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
          {risk.level === 'HIGH' && (
            <li style={{ color: 'var(--neon-red)', fontWeight: 'bold' }}>{t(lang, 'immediateAction')}: {t(lang, 'urgentRef')}</li>
          )}
          {getRecommendationsArray().map((rec, i) => (
             (risk.level !== 'HIGH' || i > 0) && <li key={i}>{rec}</li>
          ))}
        </ul>
      </div>

      <div style={{ marginTop: '2.5rem', textAlign: 'center' }}>
        <button onClick={downloadReport} className="btn btn-neon" style={{ fontWeight: 'bold' }}>
          ↓ {t(lang, 'downloadReport')}
        </button>
      </div>
    </div>
  );
}
